# Generated by Django 4.2.3 on 2023-07-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='userType',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('shop_owner', 'Shop Owner')], default='admin', max_length=20, verbose_name='User Type'),
        ),
    ]
