# Generated by Django 4.2.3 on 2023-07-20 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_custom_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='shopId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='Shop ID'),
        ),
    ]
