# Generated by Django 4.2.3 on 2023-07-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_custom_user_shopid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='userType',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('shop_owner', 'Shop Owner')], default='customer', max_length=20, verbose_name='User Type'),
        ),
    ]
