# Generated by Django 4.2.3 on 2023-07-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'required': 'This field is required.', 'unique': 'This category name is already taken.'}, max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.CharField(error_messages={'required': 'This field is required.'}, max_length=100, verbose_name='Description')),
                ('shopId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='Shop ID')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categoryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Category ID'),
        ),
    ]
