# Generated by Django 4.2.3 on 2023-07-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_image_urls_product_poster_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProps',
            fields=[
                ('shopPropsId', models.AutoField(primary_key=True, serialize=False)),
                ('props', models.JSONField(blank=True, default=dict, null=True, verbose_name='Shop Properties')),
                ('shopId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='Shop ID')),
            ],
            options={
                'verbose_name': 'Shop Property',
                'verbose_name_plural': 'Shop Properties',
            },
        ),
    ]
